steps:
  # Step 1: Checkout the code
  - name: 'gcr.io/cloud-builders/git'
    args: ['clone', 'https://github.com/your-repo.git']

  # Step 2: Build the jar using Maven
  - name: 'gcr.io/cloud-builders/maven'
    args: ['clean', 'package', '-DskipTests']

  # Step 3: Docker build
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/your-image:latest', '.']

  # Step 4: Configure kubectl and deploy
  - name: 'gcr.io/cloud-builders/kubectl'
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'  # Set your GKE cluster's zone
      - 'CLOUDSDK_CONTAINER_CLUSTER=cloud-cluster'  # Set your GKE cluster's name
      - 'CLOUDSDK_COMPUTE_REGION=us-central1'  # Set your GKE cluster's region
    args:
      - 'get-credentials'
      - 'cloud-cluster'
      - '--zone'
      - 'us-central1-a'
      - '--project'
      - '$PROJECT_ID'

  # Step 5: Deploy to Kubernetes (use kubectl)
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'apply'
      - '-f'
      - 'k8s/deployment.yaml'


options:
  logging: CLOUD_LOGGING_ONLY
