steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/cloud-442509/my-repository/spring-boot-app:latest', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/cloud-442509/my-repository/spring-boot-app:latest']

  # Step 3: Deploy to Google Kubernetes Engine (GKE))
  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'apply'
      - '-f'
      - 'k8s/deployment.yaml'

# Optional: List the images to be used in Kubernetes deployment
images:
  - 'gcr.io/$PROJECT_ID/spring-boot-app:latest'

images:
  - 'us-central1-docker.pkg.dev/cloud-442509/spring-boot-repo/spring-boot-app:$SHORT_SHA'
options:
  logging: CLOUD_LOGGING_ONLY
