steps:
# Step 1: Build the application using Maven
- name: 'gcr.io/cloud-builders/mvn'
  args: ['clean', 'package', '-DskipTests']

# Step 2: Build Docker image and push to Google Container Registry (GCR)
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '-t'
    - 'gcr.io/442509/cloud:$SHORT_SHA'
    - '.'
- name: 'gcr.io/cloud-builders/kubectl'
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'  # Set your GKE cluster's zone
      - 'CLOUDSDK_CONTAINER_CLUSTER=cloud-cluster'  # Set your GKE cluster's name
      - 'CLOUDSDK_COMPUTE_REGION=us-central1'

# Step 3: Deploy to Google Kubernetes Engine (GKE)
- name: 'gcr.io/cloud-builders/gcloud'
  args:
    - 'container'
    - 'clusters'
    - 'get-credentials'
    - 'cloud-cluster'
    - '--zone'
    - 'us-central1-a'

- name: 'gcr.io/cloud-builders/kubectl'
  args:
    - 'set'
    - 'image'
    - 'deployment/cloud-app'
    - 'cloud-app=gcr.io/442509/cloud:$SHORT_SHA'
    - '--record'

- name: 'gcr.io/cloud-builders/kubectl'
  args:
    - 'apply'
    - '-f'
    - 'kubernetes/deployment.yaml'

- name: 'gcr.io/cloud-builders/kubectl'
  args:
    - 'apply'
    - '-f'
    - 'kubernetes/service.yaml'

# Step 4: Output the External IP of the Service
- name: 'gcr.io/cloud-builders/kubectl'
  args:
    - 'get'
    - 'service'
    - 'cloud-service'
    - '--output'
    - 'jsonpath={.status.loadBalancer.ingress[0].ip}'

options:
  logging: CLOUD_LOGGING_ONLY
