apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cloud
  template:
    metadata:
      labels:
        app: cloud
    spec:
      containers:
      - name: cloud
        image: gcr.io/YOUR_PROJECT_ID/cloud:latest
        ports:
        - containerPort: 8080
